version: "3"

services:
  drf:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/app
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - "./frontend:/usr/app/frontend"
      - "/usr/app/frontend/node_modules"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

volumes:
  node-modules:
